export enum BlueprintCategory {
  STAKING = 'staking',
  DEX = 'dex',
  LENDING = 'lending',
  BRIDGE = 'bridge',
  CDP = 'cdp',
  YIELD = 'yield',
  DERIVATIVE = 'derivative',
  YIELD_AGGREGATOR = 'yield_aggregator',
  SYNTHETICS = 'synthetics',
  INDEX = 'index',
  RWA = 'rwa',
  LIQUIDITY_MANAGER = 'liquidity_manager',
  INSURANCE = 'insurance',
  NFT_LENDING = 'nft_lending',
  LEVERAGED_FARMING = 'leveraged_farming',
  NFT_MARKETPLACE = 'nft_marketplace',
  OPTIONS = 'options',
  OPTIONS_VAULT = 'options_vault',
  STAKING_POOL = 'staking_pool',
  PREDICTION_MARKET = 'prediction_market',
  FARM = 'farm',
  UNCOLLATERALIZED_LENDING = 'uncollateralized_lending',
  RWA_LENDING = 'rwa_lending',
  GAMING = 'gaming',
  ORACLE = 'oracle',
}
